openapi: 3.0.3

info:
  title: RC Group - Common Schemas
  description: Common Schemas
  version: 1.0.0

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorData:
      type: object
      additionalProperties: false
      properties:
        code:
          type: string
          pattern: ^[A-Z]{2-15}-\d{3}
          maxLength: 18
          minLength: 5
        message:
          type: string
      required: ["code", "message"]  
    ErrorResponseBody:
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorData'
          maxItems: 5
          minItems: 1
      required:
        - "errors"
    MobileNumber:
      type: integer
      format: int64
      pattern: ^[6-9]\d{9}$
      maximum: 9999999999
      minimum: 6000000000
    UserType:
      type: string
      enum:
        - ADMIN
        - ADMIN_STAFF
        - SALESMAN
        - CUSTOMER
    Id:
      type: string
    Timestamp:
      type: number
      description: EPOCH number
    ObjectMetaInfo:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: "common_schemas-contract.yml#/components/schemas/Id"
        createdOn:
          $ref: "common_schemas-contract.yml#/components/schemas/Timestamp"
        updatedOn:
          $ref: "common_schemas-contract.yml#/components/schemas/Timestamp"
      required: ["id", "createdOn", "updatedOn"]
    