openapi: 3.0.3

info:
  title: RC Group
  version: 1.0.0

servers:
  - url: https://auth.rcgroup.client.embrays.live
    description: Production server (uses live data)
  - url: https://auth-dev.rcgroup.client.embrays.live
    description: Development server (uses test data)

paths:
  /v1/categories: 
    get:
      summary: 'Get root level categories'
      operationId: getAllRootCategories
      responses:
        '200':
          description: 'Get Root Categories Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryListResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /v1/categories/{categoryId}/subcategories:
    get:
      summary: Get all subcategories of this category
      operationId: getAllChildCategories
      responses:
        '200':
          description: 'Get Child Categories Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryListResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /v1/categories/{categoryId}/products:
    get:
      summary: Gets all products related which belong to that subcategory
      operationId: getAllProducts
      responses:
        '200':
          description: 'Get All Product Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /v1/products/{productId}:
    get:
      summary: Get Details of Individual Product
      operationId: getProductDetails
      responses:
        '200':
          description: 'Get Individual Product Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
    delete:
      summary: Delete Individual Product
      responses:
        '204':
          description: 'Delete Product'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/schemas/DeleteProductResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
    post:
      summary: Admin can update details of individual product
      operationId: updateProductDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequestBody'
      responses:
        '200':
          description: 'Update Individual Product Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductDetailsResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody' 
  /v1/products/upload:
    post:
      summary: Admin can upload excel
      operationId: groupUpdateProductDetails
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/GroupUpdateProductRequestBody'
      responses:
        '204':
          description: 'Group Update Product Details'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/s/GroupUpdateProductResponseBody'
        'default':
          description: 'Server Error'
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorData:
      type: object
      additionalProperties: false
      properties:
        code:
          type: string
          pattern: ^[A-Z]{2-15}-\d{3}
          maxLength: 18
          minLength: 5
        message:
          type: string
      required:
        - "code"
        - "message"
    CategoryListResponseBody:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/Category'
    ProductsResponseBody:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/Product'
    ErrorResponseBody:
      type: object
      additionalProperties: false
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorData'
          maxItems: 5
          minItems: 1
      required:
        - "errors"
    id:
      type: string
    name:
      type: string
    mrp:
      type: integer
    scheme:
      type: string
    availaibleQty:
      type: integer 
    partNumber:
      type: string
    productDescription:
      type: string
    productApplication:
      type: string
    pictureURL: 
      type: string
    Category:
      type: object
      additionalProperties: false
      properties: 
        id:
          $ref: '#/components/schemas/id'
        name:
          type: string
      required:
        - "id"
        - "name"
    Product:
      type: object
      additionalProperties: false
      properties: 
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        mrp:
          $ref: '#/components/schemas/mrp'
        scheme:
          $ref: '#/components/schemas/scheme'
        availaibleQty:
          $ref: '#/components/schemas/availableQty'
        partNumber:
          $ref: '#/components/schemas/partNumber'
        productDescription:
          $ref: '#/components/schemas/productDescription'
        productApplication:
          $ref: '#/components/schemas/productApplication'
        pictureURL: 
          $ref: '#/components/schemas/pictureURL'
        CategoryListResponseBody:
          $ref: '#/components/schemas/CategoryListResponseBody'




