openapi: 3.0.3

info:
  title: RC Group - Auth
  description: Authentication & Authorisation service
  version: 1.0.0

servers:
  - url: https://api.rcgroup.client.embrays.live/auth
    description: Production server (uses live data)
  - url: https://api-dev.rcgroup.client.embrays.live/auth
    description: Development server (uses test data)

paths:
  /v1/login:
    post:
      security: 
        - {}
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      responses:
        '200':
          description: 'Successful login'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseBody'
        'default':
          description: 'Unsuccessful login - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/token:
    post:
      security:
        - BearerAuth: []
      operationId: refreshAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequestBody'
      responses:
        '200':
          description: 'Successful token refresh'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefreshResponseBody'
        'default':
          description: 'Unsuccessful login - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/token/v1/decrypt:
    post:
      security:
        - {}
      operationId: decryptTokenData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DecryptTokenRequestBody"
      responses:
        '200':
          description: 'Successful token validation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        'default':
          description: 'Unsuccessful login - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  
  /v1/register:
    post:
      description: Register a new user
      operationId: registerUser
      security:
        - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequestBody'
      responses:
        '200':
          description: 'Successfully created user'
          content:
            application/json: 
              schema:
                $ref: "#/components/schemas/User"
        'default':
          description: 'Unsuccessful user creation - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/mobile-number/v1/verify:
    post:
      description: Verify Mobile Number
      operationId: verifyMobileNumber
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyMobileNumberRequestBody"
      responses:
        '204':
          description: Successfully verified mobile number
        'default':
          description: 'Unsuccessful user creation - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
        
  /v1/forgot-password:
    post:
      description: User forgot password
      operationId: forgotPassword
      security:
        - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequestBody'
      responses:
        '204':
          description: 'Successfully raised forgot password request'
        'default':
          description: 'Unsuccessful request - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/forgot-password/v1/otp:
    post:
      description: User forgot password. OTP verification
      operationId: forgotPasswordOtpVerification
      security:
        - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordOtpVerificationRequestBody'
      responses:
        '204':
          description: 'Successfully verified the user. Will allow user to reset password!'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ForgotPasswordOtpVerificationResponseBody"
        'default':
          description: 'Unsuccessful request - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/reset-password:
    post:
      description: Allow user to reset password
      operationId: resetPassword
      security:
        - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequestBody'
      responses:
        '204':
          description: 'Successfully reset user password'
        'default':
          description: 'Unsuccessful request - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  
  /v1/reset-mobile-number:
    post:
      description: Reset mobile number of user
      operationId: resetMobileNumber
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetMobileNumberRequestBody'
      responses:
        '204':
          description: 'Successfully sent otp for new mobile number'
        'default':
          description: 'Unsuccessful request - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'
  /v1/reset-mobile-number/v1/resend-otp:
    post:
      description: Resend otp to the mobile number of a user
      operationId: resendOtp
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendOtpRequestBody'
      responses:
        '204':
          description: 'Successfully re-sent otp for mobile number'
        'default':
          description: 'Unsuccessful request - User/Server Error'
          content:
            application/json: 
              schema:
                $ref: 'common_schemas-contract.yml#/components/schemas/ErrorResponseBody'

components:
  securitySchemes:
    BearerAuth:
      $ref: "common_schemas-contract.yml#/components/securitySchemes/BearerAuth"
  schemas:
    LoginRequestBody:
      type: object
      additionalProperties: false
      properties:
        mobileNumber:
          $ref: 'common_schemas-contract.yml#/components/schemas/MobileNumber'
        password:
          type: string
      required:
        - "mobileNumber"
    LoginResponseBody:
      type: object
      additionalProperties: false
      properties:
        token:
          type: string
        refreshToken:
          type: string
      required:
        - "token"
        - "refreshToken"
    TokenRefreshRequestBody:
      type: object
      additionalProperties: false
      properties:
        refreshToken:
          type: string
      required:
        - "refreshToken"
    TokenRefreshResponseBody:
      type: object
      additionalProperties: false
      properties:
        token:
          type: string
      required:
        - "token"
    DecryptTokenRequestBody:
      type: object
      additionalProperties: false
      properties:
        token: 
          type: string
      required: ["token"]
    UserRegistrationRequestBody:
      type: object
      additionalProperties: false
      properties:
        userType:
          $ref: "common_schemas-contract.yml#/components/schemas/UserType"
        mobileNumber:
          $ref: 'common_schemas-contract.yml#/components/schemas/MobileNumber'
        password:
          $ref: '#/components/schemas/Password'
      required: [userType, mobileNumber, password]
    VerifyMobileNumberRequestBody:
      type: object
      additionalProperties: false
      properties:
        otp: 
          $ref: "#/components/schemas/Otp"
        mobileNumber:
          $ref: "common_schemas-contract.yml#/components/schemas/MobileNumber"
      required: [otp, mobileNumber]
    ForgotPasswordRequestBody:
      type: object
      additionalProperties: false
      properties:
        userType:
          $ref: 'common_schemas-contract.yml#/components/schemas/UserType'
        mobileNumber:
          $ref: 'common_schemas-contract.yml#/components/schemas/MobileNumber'
      required: [userType, mobileNumber]
    ForgotPasswordOtpVerificationRequestBody:
      type: object
      additionalProperties: false
      properties:
        userType:
          $ref: 'common_schemas-contract.yml#/components/schemas/UserType'
        mobileNumber:
          $ref: 'common_schemas-contract.yml#/components/schemas/MobileNumber'
        otp:
          $ref: "#/components/schemas/Otp"
      required: [userType, mobileNumber, otp]
    ForgotPasswordOtpVerificationResponseBody:
      type: object
      additionalProperties: false
      properties:
        resetPasswordKey:
          type: string
      required: [resetPasswordKey]
    ResetPasswordRequestBody:
      type: object
      additionalProperties: false
      properties:
        userType:
          $ref: 'common_schemas-contract.yml#/components/schemas/UserType'
        mobileNumber:
          $ref: 'common_schemas-contract.yml#/components/schemas/MobileNumber'
        newPassword:
          type: string
        resetKey:
          type: string
      required: [userType, mobileNumber, newPassword, resetKey]
    ResetMobileNumberRequestBody:
      type: object
      additionalProperties: false
      properties:
        mobileNumber: 
          $ref: "common_schemas-contract.yml#/components/schemas/MobileNumber"
      required: [mobileNumber]
    ResendOtpRequestBody:
      type: object
      additionalProperties: false
      properties:
        mobileNumber: 
          $ref: "common_schemas-contract.yml#/components/schemas/MobileNumber"
      required: [mobileNumber]
    Otp:
      type: integer
      format: int32
      pattern: ^\d{6}$
      maximum: 999999
      minimum: 000000
    Password:
      type: string
    User:
      type: object
      additionalProperties: false
      properties:
        userType:
          $ref: "common_schemas-contract.yml#/components/schemas/UserType"
        userId:
          $ref: "common_schemas-contract.yml#/components/schemas/Id"
        mobileNumber:
          $ref: "common_schemas-contract.yml#/components/schemas/MobileNumber"
        isVerified:
          type: boolean
      required: [userType, userId, mobileNumber, isVerified]